import React from "react";
import '@/assets/styles/global.css';

export const metadata = {
    title: 'Property Next',
    description: 'Generated by create next app',
    keywords: 'next, react, typescript, tailwindcss, vercel',
}

const MainLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <div>{children}</div>
      </body>
    </html>
  );
};

export default MainLayout;
