import React from "react";
import '@/assets/styles/global.css';
import NavBar from "@/components/NavBar";

export const metadata = {
    title: 'Property Next',
    description: 'Generated by create next app',
    keywords: 'next, react, typescript, tailwindcss, vercel',
}

const MainLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
};

export default MainLayout;
