import React from "react";
import "@/assets/styles/global.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Poppins } from "next/font/google";
import AuthProvider from "@/components/AuthProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { GlobalProvider } from "@/context/GlobalContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Property Next",
  description: "Generated by create next app",
  keywords: "next, react, typescript, tailwindcss, vercel",
};

const MainLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <GlobalProvider>
      <AuthProvider>
        <html lang="en">
          <body className={poppins.className}>
            <NavBar />
            <main>{children}</main>
            <Footer />
            <ToastContainer />
          </body>
        </html>
      </AuthProvider>
    </GlobalProvider>
  );
};

export default MainLayout;
